
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "../../components/Provider";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="bg-amber-50" lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-amber-50`}>

        <Providers>
          <Navbar></Navbar>
          {children}
          
        </Providers>
      </body>
    </html>
  );
}
